name: CI/CD - Test then Deploy (Phase 2.5)
#abc
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint CloudFormation (cfn-lint)
        run: |
          pip install cfn-lint
          cfn-lint cloudformation/template.yaml || true

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/template.yaml --region us-east-1 || true

      - name: Run pytest
        run: |
          pytest -q --junitxml=reports/junit.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/junit.xml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}
    environment:
      name: production     # ðŸ‘ˆ manual approval stage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp scripts/glue_filter_job.py s3://etl-job-for-cicd-bucket/scripts/glue_filter_job.py

      - name: Package and Deploy CloudFormation Stack
        run: |
          aws cloudformation package \
            --template-file cloudformation/template.yaml \
            --s3-bucket etl-job-for-cicd-bucket \
            --output-template-file out.yaml

          aws cloudformation deploy \
            --template-file out.yaml \
            --stack-name glue-etl-pipeline-stack \
            --capabilities CAPABILITY_IAM
