name: Deploy AWS Glue Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if needed

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp scripts/glue_filter_job.py s3://etl-job-for-cicd-bucket/scripts/glue_filter_job.py

      - name: Package and Deploy CloudFormation Stack
        run: |
          aws cloudformation package \
            --template-file cloudformation/template.yaml \
            --s3-bucket etl-job-for-cicd-bucket \
            --output-template-file out.yaml

          aws cloudformation deploy \
            --template-file out.yaml \
            --stack-name glue-etl-pipeline-stack \
            --capabilities CAPABILITY_IAM
